### ISSUE TITLE
tool_name is not a valid input

### ISSUE THREAD

**Issue by abbas-v1** [kemsakurai/action-pmd#1]
I am getting the following warning in the logs

<img width="698" alt="Screen Shot 2022-11-03 at 5 01 31 PM" src="https://user-images.githubusercontent.com/6286569/199727460-eaa42fee-2653-4ab5-b347-065dae2fcb1e.png">

**Comment by kemsakurai** [comment]
@esafzay 
Thanks for the feedback.
I've found the cause and will fix the problem.
